services:
  ### Container management Web UI
  portainer:
    container_name: ${PORTAINER_CONTAINER_NAME}
    image: portainer/portainer-ce:latest
    env_file:
      - ./.env
      - ../../.env
    ports:
      - ${PORTAINER_HOST_PORT}:9000 # webui for portainer (http)
      - ${PORTAINER_HOST_PORT_SSL}:9443 # webui for portainer (https)
    volumes:
      - ${DEFAULT_CONTAINER_DATA_LOCATION}/Portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DEFAULT_CONTAINER_DATA_LOCATION}/ssl:/ssl
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PORTAINER_CONTAINER_NAME}.rule=Host(`${PORTAINER_CONTAINER_NAME}.${PROJECT_HOSTNAME}`)"
      - "traefik.http.routers.${PORTAINER_CONTAINER_NAME}.entrypoints=https"
      - "traefik.http.routers.${PORTAINER_CONTAINER_NAME}.tls=true"
      - "traefik.http.services.${PORTAINER_CONTAINER_NAME}.loadbalancer.server.port=${PORTAINER_HOST_PORT}"
      ## Middlewares
      ###### PORTAINER HAS OAUTH BUILT IN SO THIS ISN'T NEEDED - https://docs.goauthentik.io/integrations/services/portainer/
      # - ${PORTAINER_AUTHENTIK_MIDDLEWARE:-}
    restart: unless-stopped
    networks:
      - homelab
    profiles:
      - all
      - portainer
