services:
  ############# Backups/Restore ############

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    network_mode: service:vpn
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
      - CLI_ARGS=${DUPLICATI_CLI_ARGS} #optional
    volumes:
      - ${DEFAULT_CONTAINER_DATA_LOCATION}/Duplicati:/config
      - ${DEFAULT_CONTAINER_DATA_LOCATION}/Duplicati/backups:/backups
      - ${DEFAULT_CONTAINER_DATA_LOCATION}:/source ## Access to the directory where the container AppData is located
    # ports:
    #   - ${DUPLICATI_HOST_PORT}:8200
    restart: unless-stopped
    depends_on:
      - vpn
    profiles:
      - all
      - duplicati