services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: ${HEIMDALL_CONTAINER_NAME}
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - ${DEFAULT_CONTAINER_DATA_LOCATION}/Heimdall:/config
    ports:
      - ${HEIMDALL_HOST_HTTP_PORT}:80
      - ${HEIMDALL_HOST_HTTPS_PORT}:443
    restart: unless-stopped
    profiles:
      - heimdall
      - all
