services:
  ############ Media Consumption ############

  ## NOTE - DON'T RUN EMBY AND JELLYFIN AT THE SAME TIME! THEY WILL HAVE PORT CONFLICTS!
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
      # - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ../${DEFAULT_CONTAINER_DATA_LOCATION}/Emby:/config # Configuration directory
      # - ./images/logowhite.png:/app/emby/system/dashboard-ui/modules/logoscreensaver/logowhite.png ## Uncomment and create your own logo in the image directory to customize your server
      # - ./images/logowhite.png:/app/emby/system/dashboard-ui/modules/themes/logowhite.png ## Uncomment and create your own logo in the image directory to customize your server
      # - ./images/logodark.png:/app/emby/system/dashboard-ui/modules/themes/logodark.png ## Uncomment and create your own logo in the image directory to customize your server
      - ${LOCAL_TV_PATH}:/media/Synology/Television # Media directory
      - ${LOCAL_MOVIES_PATH}:/media/Synology/Movies # Media directory
      - ${LOCAL_BACKUPS_PATH}:/media/Synology/Backups #Backups Directory
      - ../${DEFAULT_CONTAINER_DATA_LOCATION}/ssl:/ssl # Add SSL Certs to this directory
    ports:
      - ${EMBY_HOST_PORT}:8096 #http port
      - ${EMBY_HOST_PORT_SSL}:8920 #ssl port
    # runtime: nvidia # Expose NVIDIA GPUs if any (Apple Silicon does not use this)
    # network_mode: host # Enable DLNA and Wake-on-Lan
    # devices:
    # - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes, enable for NVIDIA Too i think?
    # - /dev/nvidia-uvm:/dev/nvidia-uvm # Added nvidia devices here
    # - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools # Added nvidia devices here
    # - /dev/nvidia-modeset:/dev/nvidia-modeset # Added nvidia devices here
    # - /dev/nvidiactl:/dev/nvidiactl # Added nvidia devices here
    # - /dev/nvidia0:/dev/nvidia0 # Added nvidia devices here
    # - /dev/nvidia1:/dev/nvidia1 # Added nvidia devices here (i have a 2nd GPU so i needed this too)
    # - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    # - /dev/video10:/dev/video10 #optional other video cards
    # - /dev/video11:/dev/video11 #optional
    # - /dev/video12:/dev/video12 #optional
    restart: unless-stopped
    profiles:
      - emby

  ## NOTE - DON'T RUN EMBY AND JELLYFIN AT THE SAME TIME! THEY WILL HAVE PORT CONFLICTS!
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ../${DEFAULT_CONTAINER_DATA_LOCATION}/Jellyfin:/config
      - ${LOCAL_TV_PATH}:/media/Synology/Television # Media directory
      - ${LOCAL_MOVIES_PATH}:/media/Synology/Movies # Media directory
      - ../${DEFAULT_CONTAINER_DATA_LOCATION}/ssl:/ssl # Add SSL Certs to this directory
    ports:
      - ${JELLYFIN_HOST_PORT}:8096
      - ${JELLYFIN_HOST_PORT_SSL}:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    profiles:
      - jellyfin

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
      - VERSION=${PLEX_VERSION}
      - PLEX_CLAIM=${PLEX_CLAIM} #optional
    ports:
      - ${PLEX_HOST_PORT}:32400
    volumes:
      - ../${DEFAULT_CONTAINER_DATA_LOCATION}/Plex:/config
      - ${LOCAL_TV_PATH}:/tv
      - ${LOCAL_MOVIES_PATH}:/movies
    restart: unless-stopped
    profiles:
      - plex

  komga: ###### NEED TO CONFIGURE LIKE UBUNTU SERVER so no data is lost
    image: gotson/komga:latest
    container_name: komga
    volumes:
      - ../${DEFAULT_CONTAINER_DATA_LOCATION}/Komga/config:/config
      - ${LOCAL_BOOKS_PATH}:/data
    ports:
      - ${KOMGA_HOST_PORT}:25600
    user: "${UID}:${GID}"
    # remove the whole environment section if you don't need it
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
      - KOMGA_LIBRARIES_SCAN_STARTUP=${KOMGA_LIBRARIES_SCAN_STARTUP}
      - KOMGA_REMEMBERME_KEY=${KOMGA_REMEMBERME_KEY}
      - JAVA_OPTS=${KOMGA_JAVA_OPTS}
    restart: unless-stopped
    networks:
      - default
