services:
  ### Container management Web UI
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - ${PORTAINER_HOST_PORT}:9000 # webui for portainer (http)
      - ${PORTAINER_HOST_PORT_SSL}:9443 # webui for portainer (https)
    volumes:
      - ${DEFAULT_CONTAINER_DATA_LOCATION}/Portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DEFAULT_CONTAINER_DATA_LOCATION}/ssl:/ssl
    restart: unless-stopped
    profiles:
      - all
      - portainer
