services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: ${PROWLARR_CONTAINER_NAME}
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - ${DEFAULT_CONTAINER_DATA_LOCATION}/Prowlarr:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROWLARR_CONTAINER_NAME}.rule=Host(`${PROWLARR_CONTAINER_NAME}.${PROJECT_HOSTNAME}`)"
      - "traefik.http.routers.${PROWLARR_CONTAINER_NAME}.entrypoints=https"
      - "traefik.http.routers.${PROWLARR_CONTAINER_NAME}.tls=true"
      - "traefik.http.services.${PROWLARR_CONTAINER_NAME}.loadbalancer.server.port=${PROWLARR_HOST_PORT}"
    ports:
      - ${PROWLARR_HOST_PORT}:9696
    restart: unless-stopped
    networks:
      - homelab
    profiles:
      - all
      - prowlarr
      - radarr
      - sonarr
