services:
  ############ Media PVR Management - TV SHOWS############
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: ${SONARR_CONTAINER_NAME}
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    volumes:
      - ${DEFAULT_CONTAINER_DATA_LOCATION}/Sonarr:/config
      - ${LOCAL_TV_PATH}:/tv # optional but needed to map external data
      - ${LOCAL_DOWNLOADS_PATH}:/downloads # optional but needed to map external data
    ports:
      - ${SONARR_HOST_PORT}:8989
      - ${SONARR_HOST_PORT_SSL}:9898 # ssl port if you enable it
    restart: unless-stopped
    depends_on:
      - prowlarr
    networks:
      - default
    profiles:
      - all
      - sonarr
