services:
  traefik:
    container_name: ${TRAEFIK_CONTAINER_NAME}
    image: traefik:latest
    hostname: ${PROJECT_HOSTNAME}
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--api.debug=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--serversTransport.insecureSkipVerify=true"
      #- "--certificatesResolvers.letsencrypt.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      # Optionally use the staging server to prevent exhausting rate limits
      - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.letsencrypt.acme.email=${CF_API_EMAIL}"
      - "--certificatesResolvers.letsencrypt.acme.storage=/acme.json"
      - "--certificatesResolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesResolvers.letsencrypt.acme.dnschallenge.provider=${ACME_DNS_CHALLENGE_PROVIDER}"
      - "--certificatesResolvers.le.acme.email=${CF_API_EMAIL}"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.delayBeforeCheck=10"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=${ACME_DNS_CHALLENGE_PROVIDER}"
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    labels:
      traefik.enable: true
      traefik.docker.network: home-media-docker_homelab
      traefik.http.routers.mydashboard.rule: "Host(`${TRAEFIK_CONTAINER_NAME}.${PROJECT_HOSTNAME}`)"
      traefik.http.routers.mydashboard.service: api@internal
    ports:
      - 80:80
      - 443:443
      - ${TRAEFIK_DASHBOARD_PORT}:8080 # dashboard port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ${TRAEFIK_CONFIG_FILE_LOCATION}:/etc/traefik/traefik.yml
      - ../acme.json:/acme.json
    profiles:
      - traefik
      - all
    networks:
      - homelab
      - default
    restart: unless-stopped
