services:
  zigbee2mqtt:
    container_name: ${ZIGBEE2MQTT_CONTAINER_NAME}
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ${DEFAULT_CONTAINER_DATA_LOCATION}/Zigbee2MQTT:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - ${ZIGBEE2MQTT_HOST_PORT}:8080
    environment:
      - TZ=${TIMEZONE}
    profiles:
      - zigbee2mqtt
      - homeAutomation
      - all
    devices:
      # Make sure this matched your adapter location
      - ${ZIGBEE_STICK_DEVICE_PATH}:/dev/ttyACM0