services:
  zwavejs:
    container_name: ${ZWAVE_JS_CONTAINER_NAME}
    image: zwavejs/zwave-js-ui:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    privileged: true
    env_file:
      - ./.env
      - ../../.env
    environment:
      - SESSION_SECRET="|_yTXKTh4~eMs17IQ+[95|KTl6EEk6"
      # - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want log times and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=${TIMEZONE}
    #network_mode: host
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - "${ZWAVE_STICK_DEVICE_PATH}:/dev/zwave"
    volumes:
      - ${DEFAULT_CONTAINER_DATA_LOCATION}/ZwaveJS:/usr/src/app/store
    ports:
      - "${ZWAVE_JS_UI_HOST_PORT}:8091" # port for web interface
      - "${ZWAVE_JS_WS_HOST_PORT}:3000" # port for Z-Wave JS websocket server
    profiles:
      - all
      - homeAutomation
      - zwavejs