services:
  ### For managing server content requests
  jellyseerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: ${JELLYSEERR_CONTAINER_NAME}
    env_file:
      - ./.env
      - ../../.env
    environment:
      - LOG_LEVEL=${JELLYSEER_LOG_LEVEL}
      - TZ=${TIMEZONE}
      - JELLYFIN_TYPE=${JELLYSEER_TYPE:-jellyfin} # default is jellyfin, but can do jellyfin|emby|plex
      - OVERSEERR_CORS_ORIGIN=http://localhost:8081
    ports:
      - ${JELLYSEERR_HOST_PORT}:5055
    volumes:
      - ${DEFAULT_CONTAINER_DATA_LOCATION}/Jellyseerr:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${JELLYSEERR_CONTAINER_NAME}.rule=Host(`${JELLYSEERR_CONTAINER_NAME}.${PROJECT_HOSTNAME}`)"
      - "traefik.http.routers.${JELLYSEERR_CONTAINER_NAME}.entrypoints=https"
      - "traefik.http.routers.${JELLYSEERR_CONTAINER_NAME}.tls=true"
      - "traefik.http.services.${JELLYSEERR_CONTAINER_NAME}.loadbalancer.server.port=${JELLYSEERR_HOST_PORT}"
      ## Middlewares
      - ${JELLYSEERR_FAIL2BAN_MIDDLEWARE:-}
    restart: unless-stopped
    networks:
      - homelab
    profiles:
      - all
      - jellyseerr
