services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      GID: "${GID-1000}"
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik"
    depends_on:  #uncomment if running traefik in the same compose file
      - 'traefik'
    volumes:
      - ./config/acquis.yaml:/etc/crowdsec/acquis.yaml
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec/
      - traefik-logs:/var/log/traefik/:ro
    networks:
      - homelab
    restart: unless-stopped
    profiles:
      - all
      - crowdsec
      - traefik

  bouncer-traefik:
    image: docker.io/fbonalair/traefik-crowdsec-bouncer:latest
    container_name: bouncer-traefik
    env_file:
      - ./.env
      - ../../.env
    environment:
      CROWDSEC_BOUNCER_API_KEY: ${CROWDSEC_BOUNCER_API_KEY:-}
      CROWDSEC_AGENT_HOST: crowdsec:8080
    networks:
      - homelab # same network as traefik + crowdsec
    depends_on:
      - crowdsec
    restart: unless-stopped
    profiles:
      - all
      - crowdsec
      - traefik
volumes:
  crowdsec-db:
  crowdsec-config:
  #traefik-logs: # this will be the name of the volume from trarfic logs
  #  external: true # remove if traefik is running on same stack