services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: ${PLEX_CONTAINER_NAME}
    env_file:
      - ./.env
      - ../../.env
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
      - VERSION=${PLEX_VERSION}
      - "ADVERTISE_IP=https://${PLEX_CONTAINER_NAME}.${PROJECT_HOSTNAME}:443"
      - PLEX_CLAIM=${PLEX_CLAIM} #optional
    ports:
      - ${PLEX_HOST_PORT}:32400
    volumes:
      - ${DEFAULT_CONTAINER_DATA_LOCATION}/Plex:/config
      - ${LOCAL_TV_PATH}:/tv
      - ${LOCAL_MOVIES_PATH}:/movies
    labels:
      ########## TODO - SETUP AUTH MIDDLEWARE
      - "traefik.enable=true"
      - "traefik.http.routers.${PLEX_CONTAINER_NAME}.rule=Host(`${PLEX_CONTAINER_NAME}.${PROJECT_HOSTNAME}`)"
      - "traefik.http.routers.${PLEX_CONTAINER_NAME}.entrypoints=https"
      - "traefik.http.routers.${PLEX_CONTAINER_NAME}.tls=true"
      - "traefik.http.services.${PLEX_CONTAINER_NAME}.loadbalancer.server.port=${PLEX_HOST_PORT}"
      ## Middlewares
      - ${PLEX_FAIL2BAN_MIDDLEWARE:-}
    restart: unless-stopped
    networks:
      - homelab
    profiles:
      - plex
