# All colon based stuff is <external>:<internal> -- external being the host machine, internal being the container itself.
# Ports in this instance cannot conflict and must be unique on the internal side.
# i.e. everything cannot run on port 8080

# version: "3.8"
services:
  ################### Home Automation #######################

  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: ${HOME_ASSISTANT_CONTAINER_NAME}
    # network_mode: host
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TIMEZONE}
    privileged: true
    volumes:
      - ../../.containers/HomeAssistant:/config
    ports:
      - ${HOME_ASSISTANT_HOST_PORT}:8123 #optional
    # devices: # use if you have a usb dongle for zwave/zigbee/matter or a harddrive or something
    #   - /path/to/device:/path/to/device #optional
    restart: unless-stopped
    networks:
      - zwave
    depends_on:
      - zwavejs
  zwavejs:
    container_name: ${ZWAVE_JS_CONTAINER_NAME}
    image: zwavejs/zwave-js-ui:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    privileged: true
    environment:
      - SESSION_SECRET="|_yTXKTh4~eMs17IQ+[95|KTl6EEk6"
      # - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want log times and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=${TIMEZONE}
    #network_mode: host
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - "${ZWAVE_STICK_DEVICE_PATH}:/dev/zwave"
    volumes:
      - ../../.containers/ZWaveJS2MQTT:/usr/src/app/store
    ports:
      - "${ZWAVE_JS_UI_HOST_PORT}:8091" # port for web interface
      - "${ZWAVE_JS_WS_HOST_PORT}:3000" # port for Z-Wave JS websocket server
  zigbee2mqtt:
    container_name: ${ZIGBEE2MQTT_CONTAINER_NAME}
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ../../.containers/Zigbee2MQTT:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - ${ZIGBEE2MQTT_HOST_PORT}:8080
    environment:
      - TZ=${TIMEZONE}
    profiles:
      - zigbee
    devices:
      # Make sure this matched your adapter location
      - ${ZIGBEE_STICK_DEVICE_PATH}:/dev/ttyACM0
networks:
  zwave:
  default:
    driver: bridge
    name: home-automation_default
