# This is a basic workflow to help you get started with Actions

name: "Startup Script"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Copy Environment File
        run: cp .env-example .env
      - name: Run startup.sh (no media server)
        run: chmod +x ./scripts/startup.sh && ./scripts/startup.sh 
      - name: Teardown Environment - Stop Containers
        run: docker stop $(docker ps -a --filter "name=vpn" -q) portainer komga sonarr radarr prowlarr jellyseerr transmission duplicati
      - name: Teardown Environment - Remove Containers
        run: docker rm $(docker ps -a --filter "name=vpn" -q) portainer komga sonarr radarr prowlarr jellyseerr transmission duplicati
      - name: Teardown Environment - Remove Images
        run: docker rmi $(docker images -q)
